openapi: 3.0.3
info:
  title: Amusnet Gaming Service
  description: Amusnet Gaming Service
  version: 1.0.0
servers:
  - url: https://challenge.dev.amusnetgaming.net
tags:
  - name: players
    description: Operations related to Players
  - name: game-activity
    description: Operations related to Gaming Activity
paths:
  /players:
    get:
      tags:
        - players
      summary: Retrieve all the players
      description: Returns all the players matching the filter
      operationId: getPlayers
      parameters:
        - name: playersFilter
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/PlayersFilter'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'

  /players/{playerId}:
    get:
      tags:
        - players
      summary: Find player by ID
      description: Returns a single player
      operationId: getPlayerById
      parameters:
        - name: playerId
          in: path
          description: ID of player to return
          required: true
          schema:
            $ref: '#/components/schemas/Id'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'

  /game-activity:
    get:
      tags:
        - game-activity
      summary: Retrieve all the game activity
      description: Returns all the game activity matching the filter
      operationId: getGameActivity
      parameters:
        - name: gameActivityFilter
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/GameActivityFilter'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GameActivity'

  /game-activity/{gameActivityId}:
    get:
      tags:
        - game-activity
      summary: Find game activity by ID
      description: Returns a single game activity
      operationId: getGameActivityById
      parameters:
        - name: gameActivityId
          in: path
          description: ID of game activity to return
          required: true
          schema:
            $ref: '#/components/schemas/Id'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameActivity'


components:
  schemas:
    Id:
      type: integer
      format: int64

    Player:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          type: string
        surname:
          type: string

    PlayersFilter:
      type: object
      properties:
        ids:
          type: array
          items:
            $ref: '#/components/schemas/Id'
        page:
          type: integer
        pageSize:
          type: integer

    GameActivity:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        playerId:
          $ref: '#/components/schemas/Id'
        betAmount:
          type: number
        winAmount:
          type: number
        currency:
          type: string

    GameActivityFilter:
      type: object
      properties:
        ids:
          type: array
          items:
            $ref: '#/components/schemas/Id'
        playerIds:
          type: array
          items:
            $ref: '#/components/schemas/Id'
        page:
          type: integer
        pageSize:
          type: integer